application: gpxtrips
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# static files
- url: /static/js
  static_dir: static/js
- url: /static/css
  static_dir: static/css
- url: /static/fonts
  static_dir: static/fonts
- url: /static/font-awesome
  static_dir: static/font-awesome
# Endpoints handler
- url: /_ah/spi/.*
  script: biketrip_api.application
- url: /tripmanager
  script: biketrip.application
  login: required
- url: /worker
#Backend handler
  script: backend.application
  login: admin
#Frontend handler
- url: /.*
  script: biketrip.application

  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
  